import type { Metadata } from "next";
import type { FC, PropsWithChildren } from "react";

import "@/tailwind.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className="min-h-screen w-screen antialiased">
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
